language: node_js
node_js:
- "16"

script: echo "Running tests against $(node -v) ..."

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      script: npm run unit-test
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
