require('./cases/xor');
// require('./cases/desEcbEncrypt');
// require('./cases/desDerive');
// require('./cases/parityFlipLessSignificantBit');
// require('./cases/padString');
// require('./cases/getPinBlock');
// require('./cases/encodePinBlock');
// require('./cases/decimalToKey');
// require('./cases/getPin');
// require('./cases/cardMasterKeyDerivation');
// require('./cases/cardCommonSessionKeyDerivation');
// require('./cases/signData');
// require('./cases/deriveRuntimeCardKeys');
// require('./cases/cryptogramVersionCalcTagValue');
